### ISSUE TITLE
Error reading pairs [ValueError: cannot set WRITEABLE flag to True of this array]

### ISSUE THREAD

**Issue by manyids2** [vcg-uvic/sfm_benchmark_release#1]
Got the following error(using python 3.6) while loading pairs in the parse_data.ipynb, line, 
`pairs = dd.io.load(src + '/dense/stereo/pairs-dilation-0.00-fixed2.h5')`
error:
`ValueError: cannot set WRITEABLE flag to True of this array`

Found a fix here:
[issues/24839](https://github.com/pandas-dev/pandas/issues/24839)

Basically, use numpy < 1.15 (worked for me with conda install numpy==1.14.3)

**Comment by etrulls** [comment]
I forgot to comment. Thanks for catching this, I haven't run into it, but others might. I made a note on the README and I will close this for now.
