### ISSUE TITLE
Download link

### ISSUE THREAD

**Issue by ckcraig01** [vcg-uvic/sfm_benchmark_release#2]
Dear Author:

Download link for the test data: 450 Mb => this is ok for me

Download link for the training data: 127 Gb => this link failed for me.

May you help to check whether the link for training data is ok?

Thank you!

**Comment by etrulls** [comment]
It was just missing a colon, the correct link is the one on the main
website: https://gfx.uvic.ca/nextcloud/index.php/s/75JNSoggacQhOkQ

**Comment by ckcraig01** [comment]
Thanks it works
