### ISSUE TITLE
Download link for the training data is failed.

### ISSUE THREAD

**Issue by dontLoveBugs** [vcg-uvic/sfm_benchmark_release#5]
Download link for the training data is failed. Is the training data available？

**Comment by etrulls** [comment]
Nextcloud (where we store the data) has been down for about a week, they're having some sort of problem. They're working on it but I'm not sure what the timeline is, since I'm not at UVIC. Hopefully it'll be resolved soon. The data is too large to be stored anywhere else...

**Comment by dontLoveBugs** [comment]
> Nextcloud (where we store the data) has been down for about a week, they're having some sort of problem. They're working on it but I'm not sure what the timeline is, since I'm not at UVIC. Hopefully it'll be resolved soon. The data is too large to be stored anywhere else...

Could you provide any other approach to download the training data？

**Comment by etrulls** [comment]
I don't have the resources to upload it anywhere else right now, sorry. I'll let you know if anything changes.

**Comment by kmyi** [comment]
It seems that the situation is worse than we thought. We have to fresh-install nextcloud and bring back data from our backups... We expect at least another week until it goes live. Do you have an file storage service that we can upload the training data to? I can send it there directly. It's about 150G total.

**Comment by dontLoveBugs** [comment]
> It seems that the situation is worse than we thought. We have to fresh-install nextcloud and bring back data from our backups... We expect at least another week until it goes live. Do you have an file storage service that we can upload the training data to? I can send it there directly. It's about 150G total.


Is Google dirve a good choice？I have a google drive with 200g storage.

**Comment by kmyi** [comment]
Can you drop me an email with a link to a folder that I could upload to?

**Comment by etrulls** [comment]
Data is back up again: https://vision.uvic.ca/imw-challenge/index.md
